### ISSUE TITLE
Throw Error instances so that stack trace is maintained

### ISSUE THREAD

**Issue by kevinbarabash** [infusion/Fraction.js#11]
I was trying to debug an issue in my code that caused `throwInvalidParam` to be called.  Unfortunately throwing a string doesn't maintain the callstack.  Thankfully the fix is pretty easy:
```
function throwInvalidParam() {
    throw new Error("Invalid Param");
}
```

**Comment by infusion** [comment]
The pull request was merged and version 4.0.0 was published. Thanks for pointing on this again!
