### ISSUE TITLE
v4.0.1 broken in browsers due to non standard space character

### ISSUE THREAD

**Issue by josdejong** [infusion/Fraction.js#13]
It looks like there is a non-standard space character at line 760, between the `}` and `else`:

```js
        str+= ")";
      } else {
        for (var i = dec; N && i--; ) {
          str+= N / D | 0;
```

https://github.com/infusion/Fraction.js/blob/master/fraction.js#L760

because of that I can't load the library in a browser

**Comment by infusion** [comment]
Sorry, we had this before already. That happens when typing too fast and keeping alt-key half down. It should be no problem when using the minimized version. But it's as good as fixed.

**Comment by josdejong** [comment]
thanks for your fast reply!

I haven't seen that `toString` is faster now, but that's good news of course :)
