### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by waitingcheung** [infusion/Fraction.js#14]
The constructor ``new Fraction(...);`` can take a string as the parameter, but it seems that it does not handle an empty string. I expect calling ``new Fraction("");`` to either throw an error such as [InvalidParameter](https://github.com/infusion/Fraction.js/blob/master/fraction.js#L83) or return a default value. However, the following TypeError occurs.

```
/path/fraction.js:187
          if (B[A] === '-') {// Check for minus sign at the beginning
               ^

TypeError: Cannot read property '0' of null
    at parse (/path/fraction.js:187:16)
    at Fraction (/path/fraction.js:331:5)
```

**Comment by infusion** [comment]
Thanks for this base case. Good finding!
