### ISSUE TITLE
Publish code on npm as ES5

### ISSUE THREAD

**Issue by jeongsd** [infusion/Fraction.js#18]
Hi i'm use `fraction.js` with [create-react-app](https://github.com/facebook/create-react-app)
but when i run build script in CRA it throw fails to minify error

So CRA recommend that publish npm with es5.

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

You can see detail this issue
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Thank you for making a good library.

**Comment by zenoven** [comment]
We have the same issue when using version 4.0.7

**Comment by infusion** [comment]
Thanks for the issue. Could you please give me an example snippet to compile? Fraction.js is using es5 and CommonJS pattern.

**Comment by infusion** [comment]
I just tested it with a new react installation:

```
import Fraction from 'fraction.js'
```

and after that 

```
let x = new Fraction("1/2");
```

works fine

**Comment by zenoven** [comment]
this is the output of my build scripts 
```shell
➜  proj git:(master) npm run build

> @ build /Users/zenoven/w/hannan_huifeng_website
> cross-env API_ENV=production roadhog build && cp -r ./src/assets dist

Creating an optimized production build...
Failed to compile.

index.js from UglifyJs
Unexpected token: name (P) [index.js:97217,6]
npm ERR! Darwin 17.4.0
npm ERR! argv "/Users/zenoven/.nvm/versions/node/v6.9.1/bin/node" "/Users/zenoven/.nvm/versions/node/v6.9.1/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
...

```

the code in  [index.js:97217,6] is below and the code is not compiled to ES5

![image](https://user-images.githubusercontent.com/1305982/38498361-c9dde444-3c36-11e8-94b9-a3b419d49c2b.png)

**Comment by infusion** [comment]
Thanks, I'm on it. I firstly tested execution only and it worked fine. But building is strange.

**Comment by infusion** [comment]
Ahh, I think the problem are the "let" and "const" keywords. Could you please try a changed package.json file of fraction.js by changing the following line of `node_modules/fraction.js/package.json` from

```
"main": "fraction",
```

to

```
"main": "fraction.min.js",
```

**Comment by zenoven** [comment]
@infusion yes, change the main value solved the problem

**Comment by infusion** [comment]
Should be fixed in the latest version
