### ISSUE TITLE
Feature request: LessThan

### ISSUE THREAD

**Issue by crepererum** [infusion/Fraction.js#2]
It would be helpful to be able to sort the numbers.

**Comment by infusion** [comment]
Hi,
there is the equals() method already and I replaced that with a compare() method, which will result in <0, >0 or =0. Will that help, so I'll publish this code earlier.

Robert

**Comment by crepererum** [comment]
As far as I understood there will be following mapping:
 - <0 => less then
 - =0 => equals
 - >0 => more then

That would definitely help. But can you please do NOT remove the equals() method? (Or implement it using the compare method). It makes code way more readable when only a simple equality check is required. Compare `delta.equals(zero)` against `delta.compare(zero) === 0` (where `delta` comes from e.g. a loop and not a simple `.sub(...)`). Thanks.

**Comment by infusion** [comment]
You're absolutely right. I'll backport the equals method and publish a compare method, which will work exactly the way you described. 

Robert

**Comment by infusion** [comment]
Okay, I just published 1.7.0, which got a compare() method.
