### ISSUE TITLE
.toString() method sometimes increases the number by 0.9999...

### ISSUE THREAD

**Issue by QuteBits** [infusion/Fraction.js#21]
if you take a number like `(new Fraction({ s: 1, n: 211161308301803970, d: 2346236758908933 })).toString()` which is essentially exactly 90 (did my calculations on paper) - then while casting it to string using the `.toString()` function, it will return "90.9999...":

- the characteristic (whole part of the number) is calculated by the line `str += N / D | 0;` (which, because float division is involved, will round up for 90)
- 2 lines later, the mantissa part (decimal points) is calculated further, starting with `N %= D;` line - which incorrectly starts to create a long tail of trailing 9's at the end

The combined result (90.9999...) is bad for two reasons:

1) Those 2 lines in combination are not dependant on eachother. Proposed fix:

```
      var characteristic = N / D | 0;
      str += characteristic;

      N -= characteristic * D;
      N %= D;
```

vs.

```
      str += N / D | 0;

      N %= D;
```

It doesn't remove the floating arithmetic errors from the equation but at least does not introduce an additional gap of potentially huge errors.

2) The integers being used in the example turned out to be > 2^53 which is the limit of integer-arithmetic precision for 64-bit floats... (try `Math.pow(2, 53) === Math.pow(2, 53) + 1`) So yeah, the solution for that will probably be to introduce bignumber as the fundamental value. I'd really like to say it only happens in rare cases but I can't - doing a couple of simple .mult / .div operations on quite simple fractions may quickly lead you into huge nominator/denominator integers.

**Comment by infusion** [comment]
Yes, the numbers are greater than `Number.MAX_SAFE_INTEGER`, which introduces problems as of now. Your quick fix is nice and totally makes sense. However, I hope it's not a show stopper for you when I not implement this fix. I work locally on a port to use BigInt as mentioned in #12. So, the problem should be obsolete as soon as the integer limit does not exist anymore.

**Comment by infusion** [comment]
Please see #28

**Comment by QuteBits** [comment]
Man, you're awesome!
