### ISSUE TITLE
Muller's recurrence formula

### ISSUE THREAD

**Issue by adilullo** [infusion/Fraction.js#22]
I tested the recurrence formula reported in https://medium.com/@bellmar/is-cobol-holding-you-hostage-with-math-5498c0eb428b and it appears to me that iteration 11 Fraction.js suddenly goes wrong.
It should pass from "24502636/4912337" to "122336033/24502636" and instead it returns "150238955334780/30091301355083".
Could you please also make this check?
For reference my code is below (Chrome 68):

repeat = (n,f) => {[...Array(n)].forEach(f)};
muller = (y, z) => Fraction(108)
	.sub(
		Fraction(815).sub(
			Fraction(1500)
			.mul(z.inverse())
		)
		.mul(y.inverse())
	);
x = [Fraction(4.25), Fraction(4)];
repeat(30, _ => x.unshift(muller(x[0], x[1])));
xf = x.map(_ => [_.toFraction(), _.toString()] );
console.table(xf.reverse());

**Comment by infusion** [comment]
Thanks, this is a problem due to the maximum integer number that can be handled with JavaScript. As noted in #12, I'm working on a implementation based on BigInt. With support of the infinitely large integer, we can avoid problems like reported here and in #21.

**Comment by infusion** [comment]
Please see #28
