### ISSUE TITLE
Implement a .valueOf() method returning the number

### ISSUE THREAD

**Issue by josdejong** [infusion/Fraction.js#3]
Thanks for this library, it looks solid. I'm experimenting with integrating fraction.js into math.js, see the [`v2_fraction`](https://github.com/josdejong/mathjs/tree/v2_fraction) branch. It works nicely!

It would be useful to define the `valueOf()` method of a Fraction to return it's decimal value (same output as `toNumber()`. That would allow JS to implicitly convert a Fraction to a number in operations like `new Fraction(1,4) + 2`.

**Comment by infusion** [comment]
Hi,

I just released 1.8 (a new minor version because of the little API change). I like the introduction of the valueOf() instead of the toNumber function.

Robert

**Comment by josdejong** [comment]
Thanks! You could keep them both, `valueOf` and `toNumber`, the latter is very explicit in what it returns whilst the former is mostly used "behind the scenes". It's your call.

**Comment by josdejong** [comment]
btw if it's a breaking change (like v1.8.0 is), shouldn't you version it v2.0.0?

**Comment by infusion** [comment]
You're welcome!

I think calling toNumber() explicitly is a quite rare use case when you can use the object directly within an expression (so thanks for the suggestion!). Maintaining a synonym function would make sense in general, but here it's fine I think to have just valueOf, which can also be called explicitly if needed.

About versioning: You're right, but I think it's the same argument as above. The toNumber function is a rare use case. If I would rename "add" or "mul" for example, then yes. For now I see the renaming of the toNumber method as a feature within the current API, and so updating to 2.0.0 would be a little too far. Don't you think so?

Robert

**Comment by josdejong** [comment]
The idea of semantic versioning only works when everybody neatly follows the conventions, so you can update v1.x without worries about anything breaking. I agree with you that the chance isn't very large in this case. But on the other hand, it only costs you 7 bytes to leave the `valueOf` method there, and you can deprecate it as soon as you've reached a v2.0.
