### ISSUE TITLE
Reduce size of npm module - use an .npmignore to remove unnecessary files

### ISSUE THREAD

**Issue by davidryan59** [infusion/Fraction.js#30]
GitHub repo should contain most things, including source code, tests, and examples. The npm module should contain only the minimal code required to make the module work, to reduce total size and increase load speed.

- I suggest adding an .npmignore file to remove all unnecessary files from the module.
- Might also want to add a .gitignore, e.g. for node_modules?
- In package.json, change the 'main' to the minified version
- Add to the .npmignore every file which is not involved in production code.
- In particular the examples and tests, those should not be in npm module.

Please add me as a collaborator on GitHub and npm if you want me to implement this on a feature branch and do pull request, it will reduce the size of my own bundle?

Thanks!

**Comment by infusion** [comment]
Thanks for the suggestion.

- .npmignore was added
- .gitignore was added
- I'm not sure if linking to min version only breaks bundlers which try to minify the code again

**Comment by infusion** [comment]
You're welcome :)

I've read through the top30 used npm packages and none of them used a minified "main" entry. Bundlers typically take this file and compress it according to the local config. So I don't get why you require such an aggressive module minimization for fraction.js. You can either use the min file or compress the file for production in your own build chain. I'm also after optimizing for code size, but of the code itself and don't get where the module size really matter for a small module like this one.

**Comment by davidryan59** [comment]
OK no problem, lets leave the minification then! Thanks for adding .gitignore and .npmignore.

Any chance of an npm patch to publish this change?

**Comment by infusion** [comment]
Done :)
