### ISSUE TITLE
Typo in README title

### ISSUE THREAD

**Issue by wlabi** [infusion/Fraction.js#31]
"Fraction.js - ℚ in JavaSript"

JavaScript?

**Comment by infusion** [comment]
ohh, thanks!!! never seen that misake

**Comment by infusion** [comment]
It's already fixed

**Comment by wlabi** [comment]
You're welcome! And thanks too for Fraction.js - we used it on Jonas Schmedtmann' advanced JS course.

**Comment by infusion** [comment]
Oh, that's interesting! Do you have a link?

**Comment by wlabi** [comment]
https://www.udemy.com/share/10008C/
[https://udemy-images.udemy.com/course/480x270/851712_fc61_5.jpg]<https://www.udemy.com/share/10008C/>

Learn Modern Javascript (Build & Test Real Apps Now)<https://www.udemy.com/share/10008C/>
Master JavaScript with the most complete course on the market! Projects, challenges, quizzes, ES6+, OOP, AJAX, Webpack
www.udemy.com


He used it in the Modern JS section

________________________________
