### ISSUE TITLE
How to handle invalid parameter error in fraction JS.

### ISSUE THREAD

**Issue by arunreghu** [infusion/Fraction.js#32]
How to handle invalid parameter error in fraction JS.

var x = Fraction("10    .25"); 

This code will produce error. Uncaught errorConstructor {name: "InvalidParameter", stack: "InvalidParameter↵....

But I need to show an alert popup when this error happens how to do that?

**Comment by infusion** [comment]
Simply wrap a try-catch blog around the function invocation like so:

try {
var frac = new Fraction("bla");
} catch (e) {
console.log("error", e);
}
