### ISSUE TITLE
Rounding bug

### ISSUE THREAD

**Issue by munrocket** [infusion/Fraction.js#34]
Bug when number of places is bigger than 21:
https://runkit.com/munrocket/fraction-js-test

Also not clear in documentation how you perform rounding, to result or to fractions?

**Comment by infusion** [comment]
The fraction gets rounded using standard `Math.round` like so:

```js
{
n: Math.round(10 ** places * n / d),
d: 10 ** places
}
```
Overdoing the number of places results therefore in the flawed behavior, as it would also without the library. If you really need >21 digits, I would convert the number to a string using `toString`, which is numerically stable. All you have to do then is:

- Check if repeating decimals are present within brackets. Append them as long as you need it
- Cut off the string after the number of places
- For last digit decide whether to round the digit up or down.

As an idea:

```
let places = 30;
let frac = fraction.toString().replace(/\((\d+)\)/, x => x.slice(1, -1).repeat(places / (x.length - 2)));
let [a, b] = frac.split("."); // split on decimal separator
let final = a + "." + b.slice(0, places); // cut off overstanding places
```

What needs to be done is rounding `b` correctly according to the last digit.

**Comment by munrocket** [comment]
Decimal.js have same API as Fraction.js and rounding simply works.
What Fraction.js is doing with this .round() function?

**Comment by infusion** [comment]
Decimal.js works on strings and does that slow processing for you. Fraction.js has a different orientation by operating safely and as fast as possible between `Number.MIN_SAFE_INTEGER` and `Number.MAX_SAFE_INTEGER`. Fraction.js ships with an experimental library called bigfraction.js, which uses the new native BitInt implementation. Maybe this is what you need here

**Comment by munrocket** [comment]
So you should add this in documentation, round can’t hold more than 16 decimal places because it relies on float64 numbers.

**Comment by munrocket** [comment]
Ok, thanks I will close the issue, hope you will fix that.

**Comment by munrocket** [comment]
round(-1) also gives wrong result by the way.

**Comment by infusion** [comment]
Why should a negative number of decimal places make any sense?

**Comment by infusion** [comment]
The documentation fix looks ok. Pls send a PR for it

**Comment by munrocket** [comment]
Ok
