### ISSUE TITLE
typescript error with mixed type

### ISSUE THREAD

**Issue by yukulele** [infusion/Fraction.js#39]
Several methods like `.mul()` or `.div()` can take as parameter a number or a fraction.

However with this code:
```typescript
import Fraction from 'fraction.js';
function foo(a: Fraction, b: number | Fraction) {
  return a.mul(b);
}
```
I get this typescript error:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'number | Fraction' is not assignable to parameter of type 'NumeratorDenominator'.
      Type 'number' is not assignable to type 'NumeratorDenominator'.ts(2769)
```
As woraround I can do this:
```typescript
import Fraction from 'fraction.js';
function foo(a: Fraction, b: number | Fraction) {
  if(b instanceof Fraction)
    return a.mul(b);
  return a.mul(b);
}
```
But I think it's useless...

**Comment by infusion** [comment]
Do you see where this problem occurs in the typescript definition? All functions use the `FractionConstructor` type, which overloads for fractions and numbers as well as others.

**Comment by infusion** [comment]
Any update on this or can the issue be closed?
