### ISSUE TITLE
a meme

### ISSUE THREAD

**Issue by m93a** [infusion/Fraction.js#44]
![196655496_4205908632788362_5518336289312711773_n.jpg](https://user-images.githubusercontent.com/1671665/125481018-89050262-4fed-461f-9934-db8ffbf1fc91.jpg)

**Comment by infusion** [comment]
:D

**Comment by Rudxain** [comment]
LMAO. I like how it cuts of before `pow`er (pun `indent`ed, lol, ok I'll stop the dad jokes)

Technically, binary fixed-point and floating-point are fractions whose denominators are constrained to only be powers of 2. So yes, floats are weaker fractions, embrace the sigma arbitrary-precision Fraction
