### ISSUE TITLE
Limit to certain precision(s)?

### ISSUE THREAD

**Issue by vanowm** [infusion/Fraction.js#45]
Sorry if this is obvious, but I can't seem to figure out how can I limit the precision of the output result in fraction to closest of  1/2, 1/4, 1/8 or 1/16, without these weird fractions such as 1/3?

**Comment by dekuenstle** [comment]
In this case, the simplest solution might be to maintain a set of valid precisions `eps` ("1/2, 1/4, 1/8 or 1/16, maybe 1/32 and 1/64"). 
You `simplify` the "weird" fraction with these  `eps` and choose the fraction with the largest `eps` with the minimal difference to the "weird" fraction.
E.g. if you simplify 0.3125 with eps=1/8, 1/16, 1/32, you get 3/8, 5/16, 10/32. Just 5/16 and 10/32 have 0 difference to 0.3125. From these two fractions, you choose the one with the larger eps -> solution is 5/16.

**Comment by vanowm** [comment]
Thank you! This will work. I wasn't sure if such feature was built-in or not.

**Comment by infusion** [comment]
You're welcome! And no, I'll add it as an example but having it as a feature of a general purpose library is a bit overkill. Thanks for using Fraction.js!

**Comment by infusion** [comment]
Just to let you know, I'll publish a new version soon which contains a new function `roundTo()`. With it you can simply do

```js
Fraction(1/3).roundTo("1/16") // 5/16
```
