### ISSUE TITLE
TypeScript doesn't like the example in the README

### ISSUE THREAD

**Issue by RedGuy12** [infusion/Fraction.js#47]
TypeScript doesn't like importing this module like
```ts
const Fraction = require('fraction.js'); // This expression is not constructable.
```
or
```ts
const { Fraction } = require('fraction.js'); // Module '"fraction.js"' has no exported member 'Fraction'.
```

You have to do
```ts
const Fraction = require('fraction.js').default;
```

However, all three work in vanilla JavaScript.

**Comment by chiprock** [comment]
Try the below 

import Fraction from "fraction.js";

**Comment by RedGuy12** [comment]
my point is that either the README.md should be updated or the typdef should be fixed

**Comment by infusion** [comment]
I would like to understand your problem. What would you propose to be changed in the typedef?

**Comment by dekuenstle** [comment]
This `import...`-line which works is not in the readme, which is why @RedGuy12  suggests changing the readme.

**Comment by infusion** [comment]
Done
