### ISSUE TITLE
bigfraction.js: rounding fractions with very large numbers

### ISSUE THREAD

**Issue by andrefs** [infusion/Fraction.js#48]
Hi, I'm not sure whether this has already been reported, but I couldn't find it on the other issues.

Currently the `round` method relies on `Math.round`, and for this it casts the fraction components to `Number`s.
This seems to break if the fraction components are large `BigInt`s.
Example:

```javascript
const f = Fraction(
  '4096521364329291093171203267930457883773806471006747502090792325598781148452473209851945763411024272894391273488328322013368343609851019491145409276190539874605556064161234242385897557393344605006326305605571158871450061093373390954679799512035955892117049982513332807024354592989233228381581210555649737459420836464060796645449', 
  '63723676445298091081155215910708472223644182207704751442955434135446516060522326437723594988807307437639337877044454216957092285156250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
);

console.log(f.round());

// RangeError: The number NaN cannot be converted to a BigInt because it is not an integer

**Comment by infusion** [comment]
Hi, yes this problem is known but I did not fix it yet. But I used the chance and did it now, thanks for bringing this up!
A new version isn't released yet (only pushed to master), could you please stress the rounding functions with further test cases? 
Thanks Robert

**Comment by andrefs** [comment]
@infusion Wow, many thanks for the super quick fix!

I've opened PR https://github.com/infusion/Fraction.js/pull/49 with a few tests. let me know if these are ok!

**Comment by infusion** [comment]
You're welcome! If you're curious, I added a derivation of the rounding algorithm

**Comment by andrefs** [comment]
Hey @infusion , any idea when you'll publish this to NPM? Many thanks!

**Comment by infusion** [comment]
Done ;)

**Comment by andrefs** [comment]
Thanks! :ok_hand:
