### ISSUE TITLE
Non-breaking-space characters in fraction.js

### ISSUE THREAD

**Issue by josdejong** [infusion/Fraction.js#5]
When running a test script I got an error `Uncaught SyntaxError: Unexpected identifier` when loading fraction.js v2.4.0. This seems to be because there are two nbsp characters (char code 160) in the code of fraction.js. When your HTML file doesn't define an encoding like UTF-8, you get this error.

The two orange blocks shows where they are in the code:

![2 nbsp characters 160](https://cloud.githubusercontent.com/assets/568626/8545508/b72837f6-24af-11e5-9bb5-d9c5ef43bdc6.png)

Should be an easy fix to replace these two non-breaking-spaces with regular spaces, so fraction.js just works fine without having to define an encoding.

**Comment by infusion** [comment]
Oh thanks, I thought I removed them. They're not contained in the min file as closure compiler removes them. It should be fixed in a minute

**Comment by infusion** [comment]
released 2.4.1

**Comment by josdejong** [comment]
thanks for the fast fix! Can you also publish on npm?

**Comment by infusion** [comment]
yep it is

**Comment by josdejong** [comment]
Thanks again!
