### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by Millerlm012** [infusion/Fraction.js#56]
This [link](https://jsperf.com/convert-a-rational-number-to-a-babylonian-fractions/28) in the README.md is bad. When used, you're presented with a 500 server error as seen below.

![Screen Shot 2022-12-08 at 11 08 04 AM](https://user-images.githubusercontent.com/44953936/206517757-13884f43-43f8-42aa-8e6c-f3462d35c4ce.png)

**Comment by infusion** [comment]
Thanks, it seems they dropped jsperf. I removed the link from the readme, thanks!
