### ISSUE TITLE
Throwing errors

### ISSUE THREAD

**Issue by Kolobok12309** [infusion/Fraction.js#58]
Current realization of throwing errors fully ignore call stack and can't be used for some debug

https://github.com/infusion/Fraction.js/blob/71e151fd5ccf542018307cee4a3639f42254d231/fraction.js#L380-L382

This errors created one time and keep in themselves call stack of this expression, not of throwing like this

https://github.com/infusion/Fraction.js/blob/71e151fd5ccf542018307cee4a3639f42254d231/fraction.js#L273

For fix it, can be used function calls like this

```js
// assign
Fraction['DivisionByZero'] = () => new Error("Division by Zero");


// usage
throw Fraction['DivisionByZero']();
```

**Comment by infusion** [comment]
A new version with this feature just landed on npm
