### ISSUE TITLE
base

### ISSUE THREAD

**Issue by yukulele** [infusion/Fraction.js#6]
Suggestion:
add support for base other than 10

example:
```javascript
new Fraction(1,18).toString(10); // "0.0(5)"
new Fraction(1,18).toString(11); // "0.(067A43)"
new Fraction(1,18).toString(12); // "0.08"
new Fraction(1,18).toString(15); // "0.0C(7)
new Fraction(1,18).toString(18); // "0.1"
new Fraction(1,18).toString(20); // "0.1(248HFB)"
```

**Comment by infusion** [comment]
what's a real-life use case for that? i haven't seen a ratio of two numbers in base 20 or even in base 16. i want the code as clean as possible, but maybe i miss something.

**Comment by Rudxain** [comment]
I like this idea, but I also agree with infusion, this may not be worth implementing if there's no reason to do so.

If rational numbers can be seen as *radix-agnostic* floating-point numerals, then supporting more than 1 base may be the most natural path to take. But "natural" is not enough justification to work on this.

Anyways, if anyone is interested, [I have a branch](https://github.com/Rudxain/Fraction.js/tree/main) dedicated to the development of this feature, for **all functions** that aren't base-agnostic. I need help with a **humongous** regex with a lot of redundancy, lol
