### ISSUE TITLE
History or changelog?

### ISSUE THREAD

**Issue by josdejong** [infusion/Fraction.js#7]
@infusion is there a changelog somewhere? What breaking changes are there in v3?

**Comment by infusion** [comment]
Hi Jos,

I plan to generate a changelog out of git, but hope this list will help you for now:

- toFraction and toLatex behavior was changed (old is still available with param=true)
- lcm function was added
- toString got a huge performance shift
- Fraction.REDUCE option was introduced to make reduction of fractions optional
- mod() works without an argument, which returns numerator % denominator
- String parser allows colon ( : ) as the separator

Robert

**Comment by josdejong** [comment]
Thanks for the quick reply!

**Comment by infusion** [comment]
You're welcome. I think I'll close this issue for the moment. I don't plan any new features soon, so having a changelog isn't worth the effort atm.
